apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpenv
  labels:
    app: httpenv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpenv
  template:
    metadata:
      labels:
        app: httpenv
    spec:
      containers:
        - name: httpenv
          image: tinegagideon/httpenv:latest
          imagePullPolicy: Always # ensure k8s pulls image every time pod starts
          securityContext:
            readOnlyRootFilesystem: true # mount container root filesystem as read-only
            runAsUser: 1000 # run container processes as non root user
            allowPrivilegeEscalation: false # prevent privilege escalation
            capabilities: # remove all linux capabilities
              drop:
                - ALL
          resources:
            limits: # limit container to 128 MiB memory and 0.5 CPU cores
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 30 # wait 30 seconds before performing the first check
            periodSeconds: 10 # repeat health check every 10 seconds
      securityContext:
        runAsNonRoot: true # ensure pods run as a non-root user

---
apiVersion: v1
kind: Service
metadata:
  name: httpenv-service
spec:
  type: NodePort
  selector:
    app: httpenv
  ports:
    - port: 8888 # port accessible within cluster
      targetPort: 8888 # port to forward traffic on pod containers
      nodePort: 30100 # port exposed on each node for outside traffic
