name: Build Docker Image

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_image:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: tinegagideon/httpenv:latest
